In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('survey_results_public.csv')
schema_df = pd.read_csv('survey_results_schema.csv')

In [3]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

### Pandas series

Objeto base dos pandas, existem dois objetos principais do pandas:
* Series
* Dataframe

In [6]:
labels = ['a', 'b', 'c']
minhaLista = [10,20,30]
arr = np.array(minhaLista)
dic = {'a': 10, 'b': 30, 'c':40}

### Criando series

In [13]:
pd.Series(data= minhaLista, index=labels)

a    10
b    20
c    30
dtype: int64

In [14]:
pd.Series(dic)

a    10
b    30
c    40
dtype: int64

In [15]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

### Operações com series

In [23]:
ser1 = pd.Series([1,2,3,4,5], index=['EUA', 'Alemanha','Brasil','Japão','Itália'])

In [24]:
ser2 = pd.Series([10,20,30,40], index=['EUA', 'Alemanha','Itália','Japão'])

### Podemos criar operações com series
O python procura pelos elementos com mesmo índice e executa a operação

In [25]:
ser1 + ser2

Alemanha    22.0
Brasil       NaN
EUA         11.0
Itália      35.0
Japão       44.0
dtype: float64

O resultado do Brasil deu NaN pois dentro da serie 2 não existe um elemento indexado por Brasil, logo ele recebe um valor NaN, e uma soma de um valor e um NaN é sempre um NaN

# Dataframes

Um dataframe deve possui um index e colunas

In [27]:
np.random.seed(101)

In [29]:
My_df = pd.DataFrame(data = np.random.randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [30]:
My_df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Entendendo o formato do nosso data frame

In [16]:
df.shape #64461 rows and 61 columns

(64461, 61)

## Selecting rows and Columns

In [4]:
df.head(3)

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN

#### Para saber os nomes das colunas usamos
df.columns

In [30]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq',
       'CompTotal', 'ConvertedComp', 'Country', 'CurrencyDesc',
       'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith',
       'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobFactors',
       'JobSat', 'JobSeek', 'LanguageDesireNextYear', 'LanguageWorkedWith',
       'MiscTechDesireNextYear', 'MiscTechWorkedWith',
       'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear',
       'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount',
       'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength',
       'Trans', 'UndergradMajor', 'WebframeDesireNextYear',
       'WebframeWorkedWith', 'WelcomeChange', 'WorkWeekHrs', 'YearsCode',
       'YearsCodePro'],
      dtype='object')

##### Podemos usar df.loc e df.iloc para selecionar dados do nosso dataFrame
df.iloc funciona bem quando queremos acessar dados usando valores inteiros e df.loc quando os dados são acessados por labels
#### iloc = Integer location

In [5]:
df.loc?

In [6]:
df.iloc?

In [7]:
df.loc[:,'MainBranch'] # Selecionando a coluna MainBranch de todas as linhas

0                           I am a developer by profession
1                           I am a developer by profession
2                              I code primarily as a hobby
3                           I am a developer by profession
4        I used to be a developer by profession, but no...
                               ...
64456                                                  NaN
64457                                                  NaN
64458                                                  NaN
64459                                                  NaN
64460                                                  NaN
Name: MainBranch, Length: 64461, dtype: object

In [8]:
df.loc[5:10,'MainBranch'] # Selecionando a coluna MainBranch das linhas de 5 a 10

5     I am a developer by profession
6     I am a developer by profession
7     I am a developer by profession
8     I am a developer by profession
9     I am a developer by profession
10    I am a developer by profession
Name: MainBranch, dtype: object

In [9]:
df.iloc[5:10,[1,2]] # Selecionando as colunas 1 e 2 e as linhas de 5 a 10

                       MainBranch Hobbyist
5  I am a developer by profession       No
6  I am a developer by profession      Yes
7  I am a developer by profession      Yes
8  I am a developer by profession       No
9  I am a developer by profession      Yes

In [10]:
df.loc[5:10, ['MainBranch', 'Hobbyist']] # Selecionando as colunas MainBranch e Hobbyist e as linhas de 5 a 10

                        MainBranch Hobbyist
5   I am a developer by profession       No
6   I am a developer by profession      Yes
7   I am a developer by profession      Yes
8   I am a developer by profession       No
9   I am a developer by profession      Yes
10  I am a developer by profession      Yes

In [27]:
df.loc[5:10, 'Hobbyist':'Country'] # Seleciona as linhas de 5 a 10 de todas as colunas entre hobbyist e country

,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country
5,No,NaN,14,NaN,NaN,NaN,Germany
6,Yes,NaN,18,Monthly,NaN,NaN,India
7,Yes,36.0,12,Yearly,116000.0,116000.0,United States
8,No,30.0,20,NaN,NaN,NaN,Tunisia
9,Yes,22.0,14,Yearly,25000.0,32315.0,United Kingdom
10,Yes,23.0,13,Yearly,31000.0,40070.0,United Kingdom

#### Podemos usar métodos do pandas juntos com as seleções de dados, um exemplo é o value_counts

In [23]:
df.loc[:, 'Hobbyist'].value_counts()

Yes    50388
No     14028
Name: Hobbyist, dtype: int64

## Dataframes indexes

In [50]:
users = {
    'login': ['ans3', 'adrn', 'drikons'],
    'email': ['ans3@cin.ufpe.br', 'adrn@gmail.com', 'drikons@gmail.com'],
    'lastName': ['Santana', 'Nascimento', 'SantaCruz']
}

In [51]:
users_df = pd.DataFrame(users)

In [52]:
users_df

     login              email    lastName
0     ans3   ans3@cin.ufpe.br     Santana
1     adrn     adrn@gmail.com  Nascimento
2  drikons  drikons@gmail.com   SantaCruz

In [54]:
users_df['email']

0     ans3@cin.ufpe.br
1       adrn@gmail.com
2    drikons@gmail.com
Name: email, dtype: object

##### Para setar uma coluna como index, apenas usamos o método .set_index(coluna)

In [55]:
users_df.set_index('email')

                     login    lastName
email
ans3@cin.ufpe.br      ans3     Santana
adrn@gmail.com        adrn  Nascimento
drikons@gmail.com  drikons   SantaCruz

##### Lembre-se o método set index não altera o data frame 'inplace' por padrão

In [56]:
users_df

     login              email    lastName
0     ans3   ans3@cin.ufpe.br     Santana
1     adrn     adrn@gmail.com  Nascimento
2  drikons  drikons@gmail.com   SantaCruz

In [57]:
users_df.set_index('login', inplace=True)

In [58]:
users_df

                     email    lastName
login
ans3      ans3@cin.ufpe.br     Santana
adrn        adrn@gmail.com  Nascimento
drikons  drikons@gmail.com   SantaCruz

##### Para visualizar os indices do data frame usa-se o método .index

In [70]:
users_df.index

Index(['ans3', 'adrn', 'drikons'], dtype='object', name='login')

#### Como o index agora são labels não podemos usar o df.loc com um valor numérico

In [73]:
users_df.loc['ans3':'adrn']

                  email    lastName
login
ans3   ans3@cin.ufpe.br     Santana
adrn     adrn@gmail.com  Nascimento

##### Por que usar index não númericos são úteis ? Veremos um exemplo usando o data frame schema survey. Este data frame possui as perguntas feitas em cada coluna do nosso data frame. Podemos setar o indice como sendo o nome das colunas do nosso data frame, desta forma ficará mais fácil procurar por uma questão.

In [76]:
schema_df

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order ...
1,MainBranch,Which of the following options best describes ...
2,Hobbyist,Do you code as a hobby?
3,Age,What is your age (in years)? If you prefer not...
4,Age1stCode,At what age did you write your first line of c...
5,CompFreq,"Is that compensation weekly, monthly, or yearly?"
6,CompTotal,What is your current total compensation (salar...
7,ConvertedComp,Salary converted to annual USD salaries using ...
8,Country,Where do you live?
9,CurrencyDesc,Which currency do you use day-to-day? If your ...
10,CurrencySymbol,Which currency do you use day-to-day? If your ...
11,DatabaseDesireNextYear,Which database environments have you done exte...
12,DatabaseWorkedWith,Which database environments have you done exte...
13,DevType,Which of the following describe you? Please se...
14,EdLevel,Which of the following best describes the high...
15,Employment,Which of the following best describes your cur...
16,Ethnicity,"Which of the following describe you, if any? P..."
17,Gender,"Which of the following describe you, if any? P..."
18,JobFactors,Imagine that you are deciding between two job ...
19,JobSat,How satisfied are you with your current job? (...
20,JobSeek,Which of the following best describes your cur...
21,LanguageDesireNextYear,"Which programming, scripting, and markup langu..."
22,LanguageWorkedWith,"Which programming, scripting, and markup langu..."
23,MiscTechDesireNextYear,"Which other frameworks, libraries, and tools h..."
24,MiscTechWorkedWith,"Which other frameworks, libraries, and tools h..."
25,NEWCollabToolsDesireNextYear,Which collaboration tools have you done extens...
26,NEWCollabToolsWorkedWith,Which collaboration tools have you done extens...
27,NEWDevOps,Does your company have a dedicated DevOps person?
28,NEWDevOpsImpt,How important is the practice of DevOps to sca...
29,NEWEdImpt,"How important is a formal education, such as a..."
30,NEWJobHunt,"In general, what drives you to look for a new ..."
31,NEWJobHuntResearch,"When job searching, how do you learn more abou..."
32,NEWLearn,How frequently do you learn a new language or ...
33,NEWOffTopic,Do you think Stack Overflow should relax restr...
34,NEWOnboardGood,Do you think your company has a good onboardin...
35,NEWOtherComms,Are you a member of any other online developer...
36,NEWOvertime,How often do you work overtime or beyond the f...
37,NEWPurchaseResearch,"When buying a new tool or software, how do you..."
38,NEWPurpleLink,You search for a coding solution online and th...
39,NEWSOSites,Which of the following Stack Overflow sites ha...
40,NEWStuck,What do you do when you get stuck on a problem...
41,OpSys,What is the primary operating system in which ...
42,OrgSize,Approximately how many people are employed by ...
43,PlatformDesireNextYear,Which platforms have you done extensive develo...
44,PlatformWorkedWith,Which platforms have you done extensive develo...
45,PurchaseWhat,"What level of influence do you, personally, ha..."
46,Sexuality,"Which of the following describe you, if any? P..."
47,SOAccount,Do you have a Stack Overflow account?
48,SOComm,Do you consider yourself a member of the Stack...
49,SOPartFreq,How frequently would you say you participate i...
50,SOVisitFreq,How frequently would you say you visit Stack O...
51,SurveyEase,How easy or difficult was this survey to compl...
52,SurveyLength,How do you feel about the length of the survey...
53,Trans,Are you transgender?
54,UndergradMajor,What was your primary field of study?
55,WebframeDesireNextYear,Which web frameworks have you done extensive d...
56,WebframeWorkedWith,Which web frameworks have you done extensive d...
57,WelcomeChange,"Compared to last year, how welcome do you feel..."
58,WorkWeekHrs,"On average, how many hours per week do you wor..."
59,YearsCode,"Including any education, how many years have y..."
60,YearsCodePro,"NOT including education, how many years have y..."

In [78]:
schema_df.set_index('Column', inplace=True)

#### Então para saber a pergunta feita para a resposta de uma coluna basta usar a label

In [87]:
schema_df.loc['JobSat','QuestionText']

'How satisfied are you with your current job? (If you work multiple jobs, answer for the one you spend the most hours on.)'

##### O pandas permite algumas operações com os indices, como ordenar

In [94]:
schema_df.sort_index(inplace=True, ascending=False) # Este não é um 'método inplace'

In [95]:
schema_df

                                                                   QuestionText
Column
YearsCodePro                  NOT including education, how many years have y...
YearsCode                     Including any education, how many years have y...
WorkWeekHrs                   On average, how many hours per week do you wor...
WelcomeChange                 Compared to last year, how welcome do you feel...
WebframeWorkedWith            Which web frameworks have you done extensive d...
WebframeDesireNextYear        Which web frameworks have you done extensive d...
UndergradMajor                            What was your primary field of study?
Trans                                                      Are you transgender?
SurveyLength                  How do you feel about the length of the survey...
SurveyEase                    How easy or difficult was this survey to compl...
Sexuality                     Which of the following describe you, if any? P...
SOVisitFreq                   How frequently would you say you visit Stack O...
SOPartFreq                    How frequently would you say you participate i...
SOComm                        Do you consider yourself a member of the Stack...
SOAccount                                 Do you have a Stack Overflow account?
Respondent                    Randomized respondent ID number (not in order ...
PurchaseWhat                  What level of influence do you, personally, ha...
PlatformWorkedWith            Which platforms have you done extensive develo...
PlatformDesireNextYear        Which platforms have you done extensive develo...
OrgSize                       Approximately how many people are employed by ...
OpSys                         What is the primary operating system in which ...
NEWStuck                      What do you do when you get stuck on a problem...
NEWSOSites                    Which of the following Stack Overflow sites ha...
NEWPurpleLink                 You search for a coding solution online and th...
NEWPurchaseResearch           When buying a new tool or software, how do you...
NEWOvertime                   How often do you work overtime or beyond the f...
NEWOtherComms                 Are you a member of any other online developer...
NEWOnboardGood                Do you think your company has a good onboardin...
NEWOffTopic                   Do you think Stack Overflow should relax restr...
NEWLearn                      How frequently do you learn a new language or ...
NEWJobHuntResearch            When job searching, how do you learn more abou...
NEWJobHunt                    In general, what drives you to look for a new ...
NEWEdImpt                     How important is a formal education, such as a...
NEWDevOpsImpt                 How important is the practice of DevOps to sca...
NEWDevOps                     Does your company have a dedicated DevOps person?
NEWCollabToolsWorkedWith      Which collaboration tools have you done extens...
NEWCollabToolsDesireNextYear  Which collaboration tools have you done extens...
MiscTechWorkedWith            Which other frameworks, libraries, and tools h...
MiscTechDesireNextYear        Which other frameworks, libraries, and tools h...
MainBranch                    Which of the following options best describes ...
LanguageWorkedWith            Which programming, scripting, and markup langu...
LanguageDesireNextYear        Which programming, scripting, and markup langu...
JobSeek                       Which of the following best describes your cur...
JobSat                        How satisfied are you with your current job? (...
JobFactors                    Imagine that you are deciding between two job ...
Hobbyist                                                Do you code as a hobby?
Gender                        Which of the following describe you, if any? P...
Ethnicity                     Which of the following describe you, if any? P...
Employment                    Which of the following best describes your cur...
EdLevel                       Which of the following best describes the high...
DevType                       Which of the following describe you? Please se...
DatabaseWorkedWith            Which database environments have you done exte...
DatabaseDesireNextYear        Which database environments have you done exte...
CurrencySymbol                Which currency do you use day-to-day? If your ...
CurrencyDesc                  Which currency do you use day-to-day? If your ...
Country                                                      Where do you live?
ConvertedComp                 Salary converted to annual USD salaries using ...
CompTotal                     What is your current total compensation (salar...
CompFreq                       Is that compensation weekly, monthly, or yearly?
Age1stCode                    At what age did you write your first line of c...
Age                           What is your age (in years)? If you prefer not...